# Uncomment the next line to define a global platform for your project
  platform :ios, '16.0'

target 'fireBaseChat' do
  use_frameworks!

# FireBase

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
 
# Facebook

pod 'FBSDKLoginKit'

# Google

pod 'GoogleSignIn'

# Other

pod 'MessageKit'
pod 'JGProgressHUD'
pod 'RealmSwift'
pod 'SDWebImage'

post_install do |installer|
  installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
             end
        end
 end
    installer.pods_project.targets.each do |target|
  end
end
end
