# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fireBaseChat' do
  use_frameworks!

# FireBase

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
 
# Facebook

pod 'FBSDKLoginKit'

# Google

pod 'GoogleSignIn'

# Other

pod 'MessageKit'
pod 'JGProgressHUD'
pod 'RealmSwift'
pod 'SDWebImage'

 

end
